name: Java CI (shareable)

# Thanks to https://github.com/apache/maven-gh-actions-shared/
on:
    workflow_call:
      inputs:
        maven-args:
          description: The arguments to pass to all Maven commands when building the code
          required: false
          default: '-D"invoker.streamLogsOnFailures"'
          type: string
  
        jdk-matrix:
          description: jdk matrix as json array
          required: false
          default: '[ "17" ]'
          type: string
  
        jdk-distribution-matrix:
          description: jdk distribution matrix
          required: false
          default: '[ "temurin" ]'
          type: string
  
        maven-matrix:
          description: The Maven version matrix as json array
          required: false
          default: '[ "3.8.8" ]'
          type: string
  
        matrix-exclude:
          description: exclude for matrix as json
          required: false
          default: '[]'
          type: string
    
        verify-goal:
          description: The Maven goal used by verify jobs
          required: false
          default: 'verify'
          type: string

env:
  GITHUBACTOR: ${{secrets.GITHUBACTOR}}
  GITHUBTOKEN: ${{secrets.GITHUBTOKEN}}
  GITHUBORG: ${{secrets.GITHUBORG}}
  SONAR_URL: ${{secrets.SONAR_URL}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  SIGN_KEY_PASS: ${{secrets.SIGN_KEY_PASS}}
  SIGN_KEY: ${{secrets.SIGN_KEY}}
  MAVENPROXY_USERNAME: ${{secrets.MAVENPROXY_USERNAME}}
  MAVENPROXY_TOKEN: ${{secrets.MAVENPROXY_TOKEN}}
  MAVEN_ARGS: --errors --batch-mode --show-version --update-snapshots --settings ci-settings.xml --color always -P github,nexus --no-transfer-progress  

# allow single build per branch or PR
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
jobs:
  # This job build, test and stage the artefact and the website for the develop branch
  maven-build-test-site:
    name: jdk-${{ matrix.jdk }}-${{ matrix.distribution }} ${{ matrix.maven }}
    # The tags to select the runner
    runs-on: [ self-hosted, Linux ]

    strategy:
        matrix:
          jdk: ${{ fromJSON( inputs.jdk-matrix ) }}
          distribution: ${{ fromJSON( inputs.jdk-distribution-matrix ) }}
          maven: ${{ fromJSON( inputs.maven-matrix ) }}
          exclude: ${{ fromJSON( inputs.matrix-exclude ) }}
  
    steps:
      ## Environment setup
      # checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setups git user name and email
      - name: Set up git User
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com        
      # Maven is not installed in self hosted
      # so we install one (see wrapper below for the right version)
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
            maven-version: ${{ matrix.maven }}  
     # Installs the JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          check-latest: true
          cache: 'maven'
      # Setup maven version as a wrapper
      - name: Set up Maven Wrapper
        run: >
          mvn ${{ env.MAVEN_ARGS }} org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper \
              -Dmaven="${{ matrix.maven }}"

      - name: Extract branch name
        shell: bash
        run: echo "MY_BRANCH=$(git rev-parse --abbrev-ref HEAD | tr / _)" >> $GITHUB_ENV

      # Build and test
      - name: Build and Test with Maven
        run: >
          ./mvnw ${{ env.MAVEN_ARGS }} -P gpgsigning  --activate-profiles jacoco \
              ${{ inputs.maven-args }} ${{ inputs.verify-goal }}

      # Check quality with SonarQube
        ### THIS STEP MUST BE ENABLED BY CONFIGURING : SONAR_URL and SONAR_TOKEN secrets.
      - name: Quality check with Sonarqube
        shell: bash
        if: env.SONAR_URL != null && env.SONAR_TOKEN != null
        run: >
          ./mvnw ${{ env.MAVEN_ARGS }} \
            -DskipTests=true \
            -Dsonar.branch.name=$MY_BRANCH \
            -activate-profiles jacoco,sonar \
            sonar:sonar

      # Stage artifact
      - name: Stage artifacts
        run: mkdir staging && find ./target -name \*.[jwe]ar -exec cp {} ./staging \; && ls staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      
      # Publish package
      - name: Publish package
        run: >
          ./mvnw ${{ env.MAVEN_ARGS }} \
            deploy
      
      ## Build and deploy project site      
      - name: Install SSH Key
        if: ${{github.ref == 'refs/heads/develop'}}
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and deploy site with Maven
        if: ${{github.ref == 'refs/heads/develop'}}
        run: >
          ./mvnw ${{ env.MAVEN_ARGS }} \
            site:site site-deploy